version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile/api.Dockerfile
    container_name: accord-server-container
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    depends_on:
      - database

  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}